apiVersion: v2
name: nginx
description: Nginx is a high-performance HTTP server and reverse proxy.
type: application
version: 0.10.0
appVersion: "1.29.7"
keywords:
  - nginx
  - web server
  - http
  - reverse proxy
  - load balancer
  - proxy
home: https://www.nginx.com
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/nginx
  - https://github.com/nginx/nginx
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.2.0"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/9fcd98c061/nginx-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: networking
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Nginx
      url: https://www.nginx.com
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/nginx
    - name: Application
      url: https://github.com/nginx/nginx
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |-
    - kind: added
      description: "Add namespaceOverride Value to all Charts that missing it"
      links:
        - name: "Pull Request"
          url: "https://github.com/CloudPirates-io/helm-charts/pull/1214"
        - name: "Changelog"
          url: "https://github.com/CloudPirates-io/helm-charts/blob/main/charts/nginx/CHANGELOG.md"
