{{- range $i, $user := .Values.customUsers }}
{{- if and $user.name (not $user.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" $ }}-custom-user-{{ $i }}-secret
  namespace: {{ include "cloudpirates.namespace" $ }}
  labels:
    {{- include "mongodb.labels" $ | nindent 4 }}
  {{- with (include "mongodb.annotations" $) }}
  annotations:
{{- . | indent 4 }}
  {{- end }}
type: Opaque
data:
  CUSTOM_DB: {{ $user.database | default $user.name | b64enc | quote }}
  CUSTOM_USER: {{ $user.name | b64enc | quote }}
  CUSTOM_PASSWORD: {{ $user.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
{{- end }}
