{{- if .Values.auth.enabled }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- with (include "mongodb.annotations" .) }}
  annotations: 
{{- . | indent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" (include "cloudpirates.namespace" .) (include "mongodb.fullname" .)) }}
  {{- $existingRootPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingRootPassword = index $existingSecret.data "mongodb-root-password" }}
  {{- end }}
  mongodb-root-password: {{ $existingRootPassword | default (.Values.auth.rootPassword | default (randAlphaNum 16) | b64enc) | quote }}
{{- end }}
{{- end }}