{{- if and (not .Values.replicaSet.enabled) (not .Values.shardedCluster.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- if or (include "mongodb.annotations" .) .Values.service.annotations }}
  annotations: 
{{- (include "mongodb.annotations" .) | indent 4 }}
  {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
{{- end }}