apiVersion: v2
name: ghost
description: A simple, powerful publishing platform that allows you to share your stories with the world.
type: application
version: 0.17.0
appVersion: "6.25.1"
keywords:
  - ghost
  - blogging
  - content management
home: https://ghost.org
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/ghost
  - https://github.com/TryGhost/Ghost
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
  - name: Gianni Carafa
    email: gianni.carafa@srf.ch
    url: https://www.srf.ch
dependencies:
  - name: common
    version: "2.2.0"
    repository: oci://registry-1.docker.io/cloudpirates
  - name: mariadb
    version: "0.4.x"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
icon: https://a.storyblok.com/f/143071/512x512/3a5c1cb0c5/ghost-logo.png
annotations:
  license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Ghost
      url: https://ghost.org
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/ghost
    - name: Application
      url: https://github.com/TryGhost/Ghost
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |-
    - kind: added
      description: "Add namespaceOverride Value to all Charts that missing it"
      links:
        - name: "Pull Request"
          url: "https://github.com/CloudPirates-io/helm-charts/pull/1214"
        - name: "Changelog"
          url: "https://github.com/CloudPirates-io/helm-charts/blob/main/charts/ghost/CHANGELOG.md"
