{{- include "mariadb.validateValues.auth" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.galera.enabled }}
  replicas: {{ .Values.galera.replicaCount }}
  {{- else }}
  replicas: 1
  {{- end }}
  serviceName: {{ include "mariadb.fullname" . }}
  selector:
    matchLabels:
      {{- include "mariadb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mariadb.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "mariadb.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with (include "mariadb.imagePullSecrets" .) }}
{{- . | nindent 6 }}
{{- end }}
      securityContext: {{ include "cloudpirates.renderPodSecurityContext" . | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      initContainers:
      {{- if .Values.galera.enabled }}
        - name: galera-config-init
          image: {{ include "mariadb.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          command:
            - /bin/bash
            - -c
            - |
              REPLICA_NUM=$(echo $HOSTNAME | grep -o '[0-9]*$')
              cp /tmp/galera-config-ro/galera.cnf /tmp/galera-config-rw/galera.cnf
              sed -i "s/REPLICA_NUM/$REPLICA_NUM/g" /tmp/galera-config-rw/galera.cnf
              chmod 644 /tmp/galera-config-rw/galera.cnf
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - name: galera-config
              mountPath: /tmp/galera-config-ro
              readOnly: true
            - name: galera-config-rw
              mountPath: /tmp/galera-config-rw
      {{- end }}
      {{- if and .Values.metrics.enabled .Values.initdbScriptsConfigMap }}
        - name: init-scripts-merge
          image: {{ include "mariadb.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          command:
            - /bin/bash
            - -c
            - |
              # Copy metrics init script first (to run before custom scripts)
              cp -L /tmp/metrics-scripts/* /tmp/merged-scripts/
              # Copy custom init scripts (dereference symlinks)
              cp -rL /tmp/custom-scripts/* /tmp/merged-scripts/
              # Ensure proper permissions for copied files
              find /tmp/merged-scripts -type f -exec chmod 755 {} \;
          volumeMounts:
            - name: exporter-init-scripts
              mountPath: /tmp/metrics-scripts
              readOnly: true
            - name: custom-init-scripts
              mountPath: /tmp/custom-scripts
              readOnly: true
            - name: merged-init-scripts
              mountPath: /tmp/merged-scripts
      {{- end }}
      containers:
        - name: mariadb
          image: {{ include "mariadb.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          {{- if .Values.command }}
          command: {{ toYaml .Values.command | nindent 12 }}
          {{- else if .Values.galera.enabled }}
          command:
            - /bin/bash
            - -c
            - source /usr/local/bin/galera-entrypoint.sh
          {{- end }}
          {{- if .Values.args }}
          args: {{ toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if or .Values.auth.enabled .Values.auth.database .Values.auth.username .Values.auth.allowEmptyRootPassword .Values.extraEnvVars .Values.galera.enabled }}
          env:
            {{- if and .Values.auth.enabled }}
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.secretName" . }}
                  key: {{ .Values.auth.secretKeys.rootPasswordKey }}
            {{- if .Values.auth.database }}
            - name: MARIADB_DATABASE
              value: {{ .Values.auth.database | quote }}
            {{- end }}
            {{- if .Values.auth.username }}
            - name: MARIADB_USER
              value: {{ .Values.auth.username | quote }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.secretName" . }}
                  key: {{ .Values.auth.secretKeys.userPasswordKey }}
            {{- end }}
            {{- end }}
            {{- if .Values.auth.allowEmptyRootPassword }}
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "1"
            {{- end }}
            {{- if .Values.galera.enabled }}
            - name: MARIADB_GALERA_CLUSTER
              value: "true"
            - name: MARIADB_GALERA_CLUSTER_NAME
              value: {{ .Values.galera.name | quote }}
            - name: MARIADB_GALERA_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MARIADB_GALERA_NODE_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.galera.sst.password }}
            - name: MARIADB_GALERA_SST_USER
              value: {{ .Values.galera.sst.user | quote }}
            - name: MARIADB_GALERA_SST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.galeraSecretName" . }}
                  key: {{ .Values.galera.sst.secretKeys.passwordKey }}
            {{- end }}
            - name: MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP
              value: {{ .Values.galera.forceSafeToBootstrap | quote }}
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.secretName" . }}
                  key: metricsExporterPassword
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
            {{- if .Values.galera.enabled }}
            - name: galera-repl
              containerPort: 4567
              protocol: TCP
            - name: galera-ist
              containerPort: 4568
              protocol: TCP
            - name: galera-sst
              containerPort: 4444
              protocol: TCP
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                {{- if and .Values.galera.enabled .Values.auth.enabled }}
                - |
                  if mariadb -uroot -p"$MARIADB_ROOT_PASSWORD" -e "SHOW STATUS LIKE 'wsrep_ready'" | grep -q ON; then
                    exit 0
                  else
                    mariadb -uroot -p"$MARIADB_ROOT_PASSWORD" -e "SHOW STATUS LIKE 'wsrep_local_state_comment'"
                    mariadb -uroot -p"$MARIADB_ROOT_PASSWORD" -e "SHOW STATUS LIKE 'wsrep_ready'"
                    echo "healthcheck failed: Galera not alive"
                    exit 1
                  fi
                {{- else }}
                - healthcheck.sh {{ if .Values.healthcheckExtraArgs }}{{ .Values.healthcheckExtraArgs }} {{ end }}--connect --innodb_initialized
                {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if and .Values.readinessProbe.enabled (not .Values.galera.enabled)}}
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - healthcheck.sh {{ if .Values.healthcheckExtraArgs }}{{ .Values.healthcheckExtraArgs }} {{ end }}--connect --innodb_initialized
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if and .Values.startupProbe.enabled (not .Values.galera.enabled)}}
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - healthcheck.sh {{ if .Values.healthcheckExtraArgs }}{{ .Values.healthcheckExtraArgs }} {{ end }}--connect --innodb_initialized
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - mountPath: /tmp
              name: tmp-volume
            {{- if or .Values.config.customConfiguration .Values.config.existingConfigMap .Values.galera.enabled }}
            - name: config
              mountPath: /etc/mysql/conf.d
            {{- end }}
            {{- if .Values.galera.enabled }}
            - name: galera-config-rw
              mountPath: /etc/mysql/mariadb.conf.d/60-galera.cnf
              subPath: galera.cnf
            - name: galera-scripts
              mountPath: /usr/local/bin/galera-entrypoint.sh
              subPath: galera-entrypoint.sh
            {{- end }}
            {{- if and .Values.metrics.enabled .Values.initdbScriptsConfigMap }}
            - name: merged-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- else if .Values.initdbScriptsConfigMap }}
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- else if .Values.metrics.enabled }}
            - name: exporter-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}
            {{- if .Values.containerSecurityContext.readOnlyRootFilesystem }}
            - name: run
              mountPath: /var/run/mysqld/
            {{- end }}
            {{- range $secret := .Values.extraSecrets }}
            - name: {{ $secret.name }}
              mountPath: {{ $secret.mountPath }}
            {{- end }}
            {{- range $config := .Values.extraConfigs }}
            - name: {{ $config.name }}
              mountPath: {{ $config.mountPath }}
            {{- end }}
            {{- range $storage := .Values.extraVolumes }}
            - name: {{ $storage.name }}
              mountPath: {{ $storage.mountPath }}
            {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ .Values.metrics.image.registry }}/{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          args: 
            - "--mysqld.username=exporter"
            - "--mysqld.address=localhost:3306"
          {{- if .Values.metrics.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.metrics.containerSecurityContext | nindent 12 }}
          {{- end }}
          env: 
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.secretName" . }}
                  key: metricsExporterPassword
          {{- with .Values.metrics.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- if .Values.metrics.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: {{ .Values.metrics.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.metrics.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.metrics.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.metrics.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.metrics.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.metrics.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: {{ .Values.metrics.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.metrics.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.metrics.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.metrics.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.metrics.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.metrics.resources }}
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        {{- if and .Values.metrics.enabled .Values.initdbScriptsConfigMap }}
        - name: merged-init-scripts
          emptyDir: {}
        {{- end }}
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- else if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
        {{- if .Values.containerSecurityContext.readOnlyRootFilesystem }}
        - name: run
          emptyDir: {}
        {{- end }}
        {{- if or .Values.config.customConfiguration .Values.config.existingConfigMap .Values.galera.enabled }}
        - name: config
          configMap:
            name: {{ include "mariadb.configMapName" . }}
        {{- end }}
        {{- if .Values.galera.enabled }}
        - name: galera-config
          configMap:
            name: {{ include "mariadb.fullname" . }}-galera
        - name: galera-config-rw
          emptyDir: {}
        - name: galera-scripts
          configMap:
            name: {{ include "mariadb.fullname" . }}-galera-scripts
            defaultMode: 0755
        {{- end }}
        {{- if .Values.initdbScriptsConfigMap }}
        - name: custom-init-scripts
          configMap:
            name: {{ include "mariadb.initdbScriptsConfigMap" . }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: exporter-init-scripts
          configMap:
            name: {{ include "mariadb.fullname" . }}-init-exporter-user
        {{- end }}
        {{- range $secret := .Values.extraSecrets }}
        - name: {{ $secret.name }}
          secret:
            secretName: {{ $secret.name }}
            defaultMode: {{ $secret.defaultMode | default 0440 }}
        {{- end }}
        {{- range $config := .Values.extraConfigs }}
        - name: {{ $config.name }}
          configMap:
            name: {{ $config.name }}
            defaultMode: {{ $config.defaultMode | default 0440 }}
        {{- end }}
        {{- range $storage := .Values.extraVolumes }}
        - name: {{ $storage.name }}
          persistentVolumeClaim:
            claimName: {{ $storage.pvcName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        {{- with $labels := merge (include "mariadb.selectorLabels" . | fromYaml) .Values.persistence.labels .Values.podLabels }}
        labels:
          {{- toYaml $labels | nindent 10 }}
        {{- end }}
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.persistence.selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  {{- end }}
