apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: minio
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.api)) }}
      nodePort: {{ .Values.service.nodePorts.api }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - port: {{ .Values.service.consolePort }}
      protocol: TCP
      name: console
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.console)) }}
      nodePort: {{ .Values.service.nodePorts.console }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
