{{- $numPolicies := len .Values.setup.policies }}
{{- $numBuckets := len .Values.setup.buckets }}
{{- $numUsers := len .Values.setup.users }}
{{- if and (not .Values.setup.existingSecret) (or (gt $numPolicies 0) (gt $numBuckets 0) (gt $numUsers 0)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}-setup
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "rustfs.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  policies: {{ .Values.setup.policies | toJson | b64enc | quote }}
  buckets: {{ .Values.setup.buckets | toJson | b64enc | quote }}
  users: {{ .Values.setup.users | toJson | b64enc | quote }}
{{- end }}
